### ISSUE TITLE
Error with ceph disabled

### ISSUE THREAD

**Issue by ant31** [Quentin-M/stackanetes-kpm#5]
parameters.yaml:
```yaml
ceph:
  # Whether or not Ceph should be used.
  enabled: false
```
```
kpm jsonnet manifest.jsonnet -x parameters.yaml
RuntimeError: RUNTIME ERROR: Binary operator + requires matching types, got null and object.
	snippet:(35:5)-(37:5)	function <anonymous>
	snippet:40:13-53	thunk <x>
	kpm-utils.libjsonnet:66:27	thunk <a>
	kpm-utils.libjsonnet:66:27-35	function <anonymous>
	kpm-utils.libjsonnet:66:27-35	function <$aux_0>
	kpm-utils.libjsonnet:66:7	function <anonymous>
	kpm.libjsonnet:153:18-41	object <anonymous>
	During manifestation	
```
